name: Auto Merge dev to main

on:
  schedule:
    - cron: '3 6 * * *' # Каждый день в 9 утра (UTC+3)
  push:
    branches:
      - dev  # Срабатывает при пушах в dev, если хотите выполнять слияние при каждом пуше в dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout main
        run: git checkout main

      - name: Pull latest changes to main
        run: git pull origin main

      - name: Merge dev into main
        run: |
          git merge origin/dev --no-ff --no-edit
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
